theme: jekyll-theme-minimal

title: Beginning Maker Techniques and Technology
logo: /img/20190119_133604thumbnail300_225.jpg
description: A PCC Winter 2019 course for students of the Opening Doors Project.
