theme: jekyll-theme-minimal

title: Beginning Maker Techniques and Technology
description: A PCC Winter 2019 course for students of the Opening Doors Project.
logo: https://github.com/jlaurentpdx/beginning-maker-tech/profile.jpg
      
