theme: jekyll-theme-minimal

title: Beginning Maker Techniques and Technology
description: A PCC Winter 2019 course for students of the Opening Doors Project.
logo: /_images/20190113_155017thumbnail300_225.jpg
      
      
      
